trigger:
  branches:
    include:
      - main

variables:
  azureServiceConnection: sample-nodejs-app-serviceconnection
  appName: sample-nodejs-app
  resourceGroup: nodejsapp
  packageFolder: $(System.DefaultWorkingDirectory)/sample-node-app
  slotName: staging

stages:
  - stage: BuildAndTest
    displayName: Build and Test
    jobs:
      - job: Build
        pool:
          vmImage: Default
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 18.x
          - checkout: self
          - script: |
              cd sample-node-app
              npm install
              npm test
            displayName: Install & Run Tests
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: sample-node-app
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/app.zip
              replaceExistingArchive: true
          - publish: $(Build.ArtifactStagingDirectory)/app.zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: BuildAndTest
    jobs:
      - deployment: DeployWebApp
        pool:
          vmImage: Default
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(azureServiceConnection)
                    appType: webApp
                    appName: $(appName)
                    package: $(Pipeline.Workspace)/drop/app.zip
                    resourceGroupName: $(resourceGroup)
                    deployToSlotOrASE: true
                    slotName: $(slotName)
