trigger:
  branches:
    include:
      - main

variables:
  azureServiceConnection: sample-nodejs-app-serviceconnection
  appName: sample-nodejs-app
  resourceGroup: nodejsapp
  slotName: staging

stages:
  - stage: BuildAndTest
    displayName: Build and Test
    jobs:
      - job: Build
        pool:
          name: ubuntu-latest   # ✅ This must match your self-hosted agent pool name
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: 18.x

          - script: |
              echo "Working directory:"
              dir $(Build.SourcesDirectory)
              cd $(Build.SourcesDirectory)/sample-app
              npm install
              npm test
            displayName: 'Install & Run Tests'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)/sample-app
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/app.zip
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)/app.zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: BuildAndTest
    jobs:
      - deployment: DeployWebApp
        pool:
          name: ubuntu-latest   # ✅ Use same pool name here
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(azureServiceConnection)
                    appType: webApp
                    appName: $(appName)
                    package: $(Pipeline.Workspace)/drop/app.zip
                    resourceGroupName: $(resourceGroup)
                    deployToSlotOrASE: true
                    slotName: $(slotName)
